FROM golang:alpine

WORKDIR /app

COPY go.mod app/go.mod

COPY go.sum app/go.sum

RUN go mod download

COPY . .

RUN go build -o ./orgApi ./cmd/main.go

EXPOSE 8080

CMD [ "./orgApi", "-env=.env.docker", "-config=config.yml"]
