services:
  organization-api:
    image: #create soon
    restart: unless-stopped
    networks:
      - orgnw
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080 # REST
    volumes:
      - ./migrations:/root/migrations
      - ./config.yml:/root/config.yml

  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: organization
      APP_DB_USER: docker
      APP_DB_PASS: docker
    networks:
      - orgnw
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local


networks:
  orgnw:
    driver: bridge